[build]
builder = "railpack"

[phases.setup]
cmds = ["npm install -g corepack", "corepack enable"]

[phases.install]
cmds = ["corepack prepare npm@10.8.2 --activate", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[env]
NODE_ENV = "development"